window._ = require 'underscore'
window.$ = require 'jquery'
window.$.deparam = require 'jquery-deparam'
require 'ngCordova'
require 'angular-activerecord'
require 'angular-http-auth'
require './app.coffee'
require './controller.coffee'
require './model.coffee'